# Generated by Django 3.0.2 on 2020-02-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200208_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Баланс пасскоинов'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(default='0', max_length=16, verbose_name='Название статической аватарки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Уровень'),
        ),
    ]
