# Generated by Django 3.0.2 on 2020-02-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=16)),
                ('lat', models.CharField(max_length=16)),
                ('long', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
    ]
